# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d9c5deef4c461419ded1d4a2e2cf184a"
name = "Journal Customizer - Sanaya"
application_url = "https://example.com"
embedded = false

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_draft_orders,write_files,write_inventory,read_inventory,read_orders,read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://journal-custom.vercel.app/api/admin/auth/shopify/callback",
  "http://localhost:3000/api/admin/auth/shopify/callback"
]
